-- =============================================================================
-- V1: Create Identity Tables (roles, users, user_roles)
-- =============================================================================
-- Ensure pgcrypto extension is available for gen_random_uuid()
-- Required on a clean PostgreSQL instance where the extension is not pre-loaded.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================================
-- Service: seller-identity-service
-- Database: identity_db
-- Conventions:
--   - UUID primary keys (generated by application, not database)
--   - TIMESTAMPTZ for all timestamps (stored in UTC)
--   - BIGINT for version column (optimistic locking)
--   - snake_case for all identifiers
--   - Every table has: id, created_at, updated_at, version
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. ROLES TABLE
-- ---------------------------------------------------------------------------
-- Reference table for platform roles. Rows are seeded in this migration and
-- referenced by user_roles. New roles require a new migration (not app code).
-- ---------------------------------------------------------------------------

CREATE TABLE roles (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    name            VARCHAR(50)     NOT NULL,
    description     VARCHAR(255),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version         BIGINT          NOT NULL DEFAULT 0,

    -- Primary key
    CONSTRAINT pk_roles PRIMARY KEY (id),

    -- Business rule: each role name must be unique across the platform
    CONSTRAINT uq_role_name UNIQUE (name)
);

-- No additional indexes needed: unique constraint on 'name' creates an implicit index.
-- Role lookups are always by name (e.g., WHERE name = 'CUSTOMER').

COMMENT ON TABLE roles IS 'Platform role definitions. Seeded via migration. Referenced by user_roles.';
COMMENT ON COLUMN roles.name IS 'Role identifier stored as string enum value (CUSTOMER, SELLER, ADMIN, SUPPORT_AGENT)';
COMMENT ON COLUMN roles.version IS 'Optimistic locking counter for concurrent modification detection';


-- ---------------------------------------------------------------------------
-- 2. USERS TABLE
-- ---------------------------------------------------------------------------
-- Core identity table for all platform users (customers, sellers, admins).
-- Stores authentication credentials and account state.
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    email           VARCHAR(320)    NOT NULL,
    password_hash   VARCHAR(256)    NOT NULL,
    first_name      VARCHAR(100)    NOT NULL,
    last_name       VARCHAR(100)    NOT NULL,
    phone_number    VARCHAR(20)     NOT NULL,
    status          VARCHAR(30)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version         BIGINT          NOT NULL DEFAULT 0,

    -- Primary key
    CONSTRAINT pk_users PRIMARY KEY (id),

    -- Business rule: one account per email address
    CONSTRAINT uq_user_email UNIQUE (email),

    -- Business rule: one account per phone number
    CONSTRAINT uq_user_phone_number UNIQUE (phone_number),

    -- Data integrity: status must be one of the defined enum values
    CONSTRAINT chk_user_status CHECK (status IN (
        'PENDING_VERIFICATION', 'ACTIVE', 'LOCKED', 'DISABLED'
    ))
);

-- Note: idx_user_email and idx_user_phone_number are NOT created explicitly
-- because the UNIQUE constraints (uq_user_email, uq_user_phone_number) already
-- create implicit B-tree indexes in PostgreSQL. Duplicate indexes would waste
-- storage and add write overhead on every INSERT/UPDATE.

-- Index: status-based filtering for admin operations
-- (find all locked users, pending verifications, etc.)
CREATE INDEX idx_user_status ON users (status);

COMMENT ON TABLE users IS 'Core identity table for all platform users. Owns credentials and account state.';
COMMENT ON COLUMN users.email IS 'Unique email address. Normalized to lowercase on write. Max 320 chars per RFC 5321.';
COMMENT ON COLUMN users.password_hash IS 'Bcrypt or Argon2 hash. Never stores plaintext passwords.';
COMMENT ON COLUMN users.status IS 'Account lifecycle state: PENDING_VERIFICATION, ACTIVE, LOCKED, DISABLED';
COMMENT ON COLUMN users.version IS 'Optimistic locking counter. Prevents lost updates on concurrent modifications.';


-- ---------------------------------------------------------------------------
-- 3. USER_ROLES TABLE (Explicit Join Entity)
-- ---------------------------------------------------------------------------
-- Many-to-many relationship between users and roles, modeled as a first-class
-- entity (not a hidden @ManyToMany join table). This allows:
--   - Auditable role assignments (created_at tracks when role was granted)
--   - Future metadata: assigned_by, expires_at, reason
--   - Explicit query and lifecycle control
-- ---------------------------------------------------------------------------

CREATE TABLE user_roles (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id         UUID            NOT NULL,
    role_id         UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    version         BIGINT          NOT NULL DEFAULT 0,

    -- Primary key
    CONSTRAINT pk_user_roles PRIMARY KEY (id),

    -- Business rule: a user cannot be assigned the same role twice
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),

    -- Referential integrity: user must exist
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,

    -- Referential integrity: role must exist
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE RESTRICT
);

-- Index: find all roles for a specific user (used on every authenticated request)
CREATE INDEX idx_user_role_user_id ON user_roles (user_id);

-- Index: find all users with a specific role (admin: "show all sellers")
CREATE INDEX idx_user_role_role_id ON user_roles (role_id);

COMMENT ON TABLE user_roles IS 'Explicit join entity for user-role assignments. Supports audit and future metadata.';
COMMENT ON COLUMN user_roles.user_id IS 'FK to users.id. CASCADE on delete: removing a user removes their role assignments.';
COMMENT ON COLUMN user_roles.role_id IS 'FK to roles.id. RESTRICT on delete: cannot remove a role that is assigned to users.';


-- ---------------------------------------------------------------------------
-- 4. SEED DATA: Platform Roles
-- ---------------------------------------------------------------------------
-- Roles are reference data managed exclusively via migrations.
-- The application never creates roles — it only reads and assigns them.
-- Adding a new role requires a new Flyway migration (V{N}__add_role_xxx.sql).
-- ---------------------------------------------------------------------------

INSERT INTO roles (id, name, description, created_at, updated_at, version) VALUES
    (gen_random_uuid(), 'CUSTOMER',      'End user who browses, purchases, and receives products',        now(), now(), 0),
    (gen_random_uuid(), 'SELLER',        'Merchant who lists products and fulfills orders',               now(), now(), 0),
    (gen_random_uuid(), 'ADMIN',         'Platform operator with full administrative access',             now(), now(), 0),
    (gen_random_uuid(), 'SUPPORT_AGENT', 'Customer support representative handling disputes and tickets', now(), now(), 0);

COMMENT ON COLUMN roles.id IS 'UUIDs generated at seed time. Application references roles by name, not by ID.';
